/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Drizzle": {
      "authToken": {
        "4dabf18193072939515e22adb298388d": string
        "packageVersion": string
        "urn": string
      }
      "type": "sst.sst.Linkable"
      "url": {
        "4dabf18193072939515e22adb298388d": string
        "packageVersion": string
        "urn": string
      }
    }
    "TursoAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
