/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FormFormIdImport } from './routes/form.$formId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormFormIdRoute = FormFormIdImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form/$formId': typeof FormFormIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/$formId': typeof FormFormIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form/$formId': typeof FormFormIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form/$formId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/$formId'
  id: '__root__' | '/' | '/form/$formId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormFormIdRoute: typeof FormFormIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormFormIdRoute: FormFormIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form/$formId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form/$formId": {
      "filePath": "form.$formId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
